In this Notebook, I am filtering OECD pharmaceutical data and creating separate CSVs for each prescription medication to visualize their prices

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('Country_Data_iFHP_Cost_Survey_2017 (1).csv')
df

,Year,Service Category,Service Type,Service,Country,Price 2017 USD,Percent of US Price
0,2017,Medical,Hospital Admissions,Inpatient Appendectomy,USA,"15,155.0",1.000000
1,2017,Medical,Hospital Admissions,Bypass Surgery,USA,"78,104.0",1.000000
2,2017,Medical,Hospital Admissions,C Section,USA,"15,034.0",1.000000
3,2017,Medical,Hospital Admissions,Normal Delivery,USA,"11,167.0",1.000000
4,2017,Medical,Hospital Admissions,Angioplasty,USA,"32,229.0",1.000000
...,...,...,...,...,...,...,...
220,2017,Drug,Prescription Drugs,Victoza 3-Pak (Liraglutide),UK,151.9,0.198249
221,2017,Drug,Prescription Drugs,Xarelto (Rivaroxaban),UK,65.0,0.171546
222,2017,Drug,Prescription Drugs,Kalydeco (Ivacaftor),UK,"18,060.0",0.756471
223,2017,Drug,Prescription Drugs,Enbrel (Etanercept),UK,922.4,0.198997
224,2017,Drug,Prescription Drugs,Harvoni (Ledipasvir/Sofosbuvir),UK,"16,761.4",0.530122

In [27]:
new_df=df[df['Service Type'] == 'Prescription Drugs']
new_df

,Year,Service Category,Service Type,Service,Country,Price 2017 USD,Percent of US Price
18,2017,Drug,Prescription Drugs,Xeljanz (Tofacitinib Citrate),USA,"3,857.0",1.000000
19,2017,Drug,Prescription Drugs,Humira Pen (Adalimumab),USA,"4,481.0",1.000000
20,2017,Drug,Prescription Drugs,Victoza 3-Pak (Liraglutide),USA,766.0,1.000000
21,2017,Drug,Prescription Drugs,Xarelto (Rivaroxaban),USA,379.0,1.000000
22,2017,Drug,Prescription Drugs,Kalydeco (Ivacaftor),USA,"23,874.0",1.000000
...,...,...,...,...,...,...,...
220,2017,Drug,Prescription Drugs,Victoza 3-Pak (Liraglutide),UK,151.9,0.198249
221,2017,Drug,Prescription Drugs,Xarelto (Rivaroxaban),UK,65.0,0.171546
222,2017,Drug,Prescription Drugs,Kalydeco (Ivacaftor),UK,"18,060.0",0.756471
223,2017,Drug,Prescription Drugs,Enbrel (Etanercept),UK,922.4,0.198997
224,2017,Drug,Prescription Drugs,Harvoni (Ledipasvir/Sofosbuvir),UK,"16,761.4",0.530122

In [30]:
print(new_df.columns)
new_df = new_df.drop(['Year', 'Service Category','Service Type'], axis=1)

Index(['Year', 'Service Category', 'Service Type', 'Service', 'Country',
       'Price 2017 USD', 'Percent of US Price'],
      dtype='object')

In [31]:
new_df

,Service,Country,Price 2017 USD,Percent of US Price
18,Xeljanz (Tofacitinib Citrate),USA,"3,857.0",1.000000
19,Humira Pen (Adalimumab),USA,"4,481.0",1.000000
20,Victoza 3-Pak (Liraglutide),USA,766.0,1.000000
21,Xarelto (Rivaroxaban),USA,379.0,1.000000
22,Kalydeco (Ivacaftor),USA,"23,874.0",1.000000
...,...,...,...,...
220,Victoza 3-Pak (Liraglutide),UK,151.9,0.198249
221,Xarelto (Rivaroxaban),UK,65.0,0.171546
222,Kalydeco (Ivacaftor),UK,"18,060.0",0.756471
223,Enbrel (Etanercept),UK,922.4,0.198997
224,Harvoni (Ledipasvir/Sofosbuvir),UK,"16,761.4",0.530122

In [41]:
services = [
    'Xeljanz (Tofacitinib Citrate)',
    'Humira Pen (Adalimumab)',
    'Victoza 3-Pak (Liraglutide) ',
    'Xarelto (Rivaroxaban)',
    'Kalydeco (Ivacaftor)',
    'Enbrel (Etanercept) ',
    'Harvoni (Ledipasvir/Sofosbuvir) '
]

# Create a dictionary to store separate DataFrames for each service
service_dfs = {}

for service in services:
    # Replace parentheses with underscores
    service_key = service.replace('(', '_').replace(')', '_').replace('/', '_')
    service_dfs[service_key] = new_df[new_df['Service'] == service]

# Save each DataFrame to a separate CSV file
for service, df in service_dfs.items():
    file_name = f"{service.replace(' ', '_')}.csv"
    df.to_csv(file_name, index=False)
    print(f"{file_name} saved successfully.")

Xeljanz__Tofacitinib_Citrate_.csv saved successfully.
Humira_Pen__Adalimumab_.csv saved successfully.
Victoza_3-Pak__Liraglutide__.csv saved successfully.
Xarelto__Rivaroxaban_.csv saved successfully.
Kalydeco__Ivacaftor_.csv saved successfully.
Enbrel__Etanercept__.csv saved successfully.
Harvoni__Ledipasvir_Sofosbuvir__.csv saved successfully.